version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    # Tell docker what file to build the server from
    build: .
    expose:
      - 5000
    # Environment variables
    environment:
      - PORT=5000
      - NODE_ENV=development
    # Port mapping
    ports:
      - 5000:5000

    # Restart action
  ##########################
  ### SETUP CLIENT CONTAINER
  ##########################
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - server

